http://www.numpy.org/devdocs/user/basics.creation.html

# Array Creation

## Converting Python array_like Objects to NumPy Arrays

In [2]:
import numpy as np

In [3]:
x = np.array([2,3,1,0])

In [4]:
x

array([2, 3, 1, 0])

In [5]:
x = np.array([2, 3, 1, 0])

In [6]:
x

array([2, 3, 1, 0])

In [7]:
x = np.array([[1,2.0],[0,0],(1+1j,3.)])

In [8]:
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

In [9]:
x = np.array([[ 1.+0.j, 2.+0.j], [ 0.+0.j, 0.+0.j], [1.+1.j, 3.+0.j]])

In [10]:
x

array([[1.+0.j, 2.+0.j],
       [0.+0.j, 0.+0.j],
       [1.+1.j, 3.+0.j]])

## Intrinsic NumPy Array Creation

In [11]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])